version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-app
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html/
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=sample
      - DATABASE_USER=sampleuser
      - DATABASE_PASSWORD=samplepass

    networks:
      - app_network

  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=sample
      - MYSQL_USER=sampleuser
      - MYSQL_PASSWORD=samplepass
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app_network

networks:
  app_network:

volumes:
  db_data:

